- name: Add an LDAP entry using Ansible
  # hosts: openldap_server
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - include_vars:
      file: "vars.yaml"
  - name: Delete JeanDupond from LDAP
    ansible.builtin.shell: |
      ldapdelete -H ldap://192.168.10.37:30389 -D "cn=admin,dc=example,dc=org" -w Not@SecurePassw0rd "cn=Jean Dupond,ou=users,dc=example,dc=org"
    register: stdout_lines
  - name: Print JeanDupond delete LDAP output
    ansible.builtin.debug:
      var: stdout_lines.stdout_lines
    when: stdout_lines is defined and stdout_lines.stdout_lines is not none