---
- name: Add an LDAP entry using Ansible
  # hosts: openldap_server
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    ansible.builtin.uri:
      method: GET
      url: http://192.168.10.37:30084
      return_content: true
    register: result

  - name: Print HTTP response
    ansible.builtin.debug:
      var: result      